services:
  - type: web
    name: wedding-rsvp-app
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wedding_db
          property: connectionString
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
  - type: postgres
    name: wedding_db
    plan: free
    databaseName: wedding
    user: wedding_user
    password: wedding_pass